apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-service
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-service
  template:
    metadata:
      labels:
        app: simple-service
    spec:
      containers:
        - name: simple-service
          image: bjy502/simle-jaeger-test:v1.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: JAEGER_AGENT_HOST
              value: "localhost"
            - name: JAEGER_AGENT_PORT
              value: "6831"
---
apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: observability
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: simple-service